# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpComingMeetups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=100)),
                ('Topic', models.CharField(blank=True, choices=[('Technical Presentation', 'TechPre'), ('Non-Technical Presentation', 'NonTechPre'), ('Talks', 'Talks')], max_length=50)),
                ('Speaker', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Date', models.DateField(default=None)),
                ('Time', models.TimeField(default=None)),
                ('Venue', models.CharField(max_length=50)),
            ],
        ),
    ]
