# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingmeetups',
            name='Topic',
            field=models.CharField(choices=[('Technical Presentation', 'Technical Presentation'), ('Non-Technical Presentation', 'Non-Technical Presentation'), ('Talks', 'Talks')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingmeetups',
            name='Venue',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
